GET  http://127.0.0.1:3000/api/mahasiswa

### login

POST http://127.0.0.1:3000/api/login
Content-Type: application/json

{
    "username" : "1121101980",
    "password" : "1121101980"
}


### buku
GET http://127.0.0.1:3000/api/buku?start=0&limit=20
### terbaru
GET http://127.0.0.1:3000/api/buku/terbaru
### terkenal
GET http://127.0.0.1:3000/api/buku/terkenal
### detil
GET http://127.0.0.1:3000/api/buku/9789794336052

## hapus buku
DELETE http://127.0.0.1:3000/api/buku/9789792965629
### tambah buku
POST http://127.0.0.1:3000/api/buku
Content-Type: application/json

{
    "isbn" : "9789792965629",
    "judul_buku" : "Java",
    "gambar_buku" : "https://iili.io/HCvr8KB.md.jpg",
    "penerbit" : "Andi Offset",
    "jumlah_halaman" : 386,
    "deskripsi" : "Java, Referensi Lengkap Untuk Programer",
    "nomor_rak" : 1,
    "pengarang" : "Andi Offset",
    "stok_buku" : 8,
    "stok_tersedia" : 8,
    "id_kategori" : 1
}

### ubah buku
PUT  http://127.0.0.1:3000/api/buku/9789792965629
Content-Type: application/json

{
    "judul_buku" : "Java",
    "gambar_buku" : "https://iili.io/HCvr8KB.md.jpg",
    "penerbit" : "Andi Offset",
    "jumlah_halaman" : 386,
    "deskripsi" : "Java, Referensi Lengkap Untuk Programer",
    "nomor_rak" : 1,
    "pengarang" : "Andi Offset",
    "stok_buku" : 12,
    "stok_tersedia" : 12,
    "id_kategori" : 1
}


### pinjam buku
GET http://127.0.0.1:3000/api/buku/pinjam/9789794336052
### buku sedang dipinjam
GET http://127.0.0.1:3000/api/buku/dipinjam?start=0&limit=10
### riwayat peminjaman buku yang sudah selesai
GET http://127.0.0.1:3000/api/buku/riwayat-peminjaman?start=0&limit=10

### selesaikan peminjaman buku
GET http://127.0.0.1:3000/api/buku/pengembalian?nim=1121101710&isbn=9789794336052