GET  http://127.0.0.1:3000/api/mahasiswa

### login

POST http://127.0.0.1:3000/api/login
Content-Type: application/json

{
    "username" : "1121101980",
    "password" : "1121101980"
}


### bukus
GET http://127.0.0.1:3000/api/buku?start=0&limit=20
###
GET http://127.0.0.1:3000/api/buku/terbaru
###
GET http://127.0.0.1:3000/api/buku/terkenal
###
GET http://127.0.0.1:3000/api/buku/pinjam/9786023749928


### detil
GET http://127.0.0.1:3000/api/buku/9786023749928


### stok sebuah buku
GET http://127.0.0.1:3000/api/buku/stok/9786023749928

### cari
GET http://127.0.0.1:3000/api/buku/cari?judul=python

### lihat daftar buku yang dipinjam
## dalam proses peminjaman = proses
## selesai proses peminjaman = selesai
GET http://127.0.0.1:3000/api/buku/pinjaman/proses
