GET  http://127.0.0.1:3000/api/mahasiswa

### login

POST http://127.0.0.1:3000/api/login
Content-Type: application/json

{
    "username" : "1121101980",
    "password" : "1121101980"
}


### buku
GET http://127.0.0.1:3000/api/buku?start=0&limit=40
### terbaru
GET http://127.0.0.1:3000/api/buku/terbaru
### terkenal
GET http://127.0.0.1:3000/api/buku/terkenal
### detil
GET http://127.0.0.1:3000/api/buku/9789794336052

### hapus buku
DELETE http://127.0.0.1:3000/api/buku/9789794336052
### tambah buku
POST http://127.0.0.1:3000/api/buku

### ubah buku
PUT  http://127.0.0.1:3000/api/buku/9789794336052
Content-Type: application/json

{
    
    "isbn": "9789794336052",
    "judul_buku": "Bj Habibie2",
    "penerbit": "Mizan",
    "jumlah_halaman": 360,
    "deskripsi": "Buku ini merangkai jejak pemikiran B.J. Habibie selama menjabat sebagai Menteri Riset dan Teknologi sejak tahun 1978 hingga Maret 1998",
    "nomor_rak": 2,
    "pengarang": "Mizan",
    "stok_buku": 12,
    "id_kategori": 2
    
}


### kategori
GET http://127.0.0.1:3000/api/buku/kategori


### pinjam buku
GET http://127.0.0.1:3000/api/buku/pinjam/9789794336052
### buku sedang dipinjam
GET http://127.0.0.1:3000/api/buku/dipinjam?start=0&limit=10
### riwayat peminjaman buku yang sudah selesai
GET http://127.0.0.1:3000/api/buku/riwayat-peminjaman?start=0&limit=10

### selesaikan peminjaman buku
GET http://127.0.0.1:3000/api/buku/pengembalian?nim=1121101710&isbn=9789794336052